'use client'

import { FormEvent, useEffect, useState } from 'react'
import { ArrowUpRight, FileText, ImagePlus, LogOut, Plus, Trash2, Upload, X } from 'lucide-react'
import { useRouter } from 'next/navigation'
import { createClient } from '@/lib/supabase/client'

type Post = { id: string; title: string; slug: string; content: string; image_url: string | null; published: boolean; created_at: string }

export default function AdminDashboard({ userEmail }: { userEmail: string }) {
  const router = useRouter(); const supabase = createClient(); const [posts, setPosts] = useState<Post[]>([]); const [showForm, setShowForm] = useState(false); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(''); const [title, setTitle] = useState(''); const [content, setContent] = useState(''); const [image, setImage] = useState<File | null>(null)
  async function loadPosts() { const { data } = await supabase.from('posts').select('id,title,slug,content,image_url,published,created_at').order('created_at', { ascending: false }); if (data) setPosts(data) }
  useEffect(() => { loadPosts() }, [])
  async function logout() { await supabase.auth.signOut(); router.replace('/admin/login') }
  async function createPost(event: FormEvent) { event.preventDefault(); setSaving(true); setMessage(''); const slug = title.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, ''); let imageUrl = null
    if (image) { const path = `${crypto.randomUUID()}-${image.name.replace(/[^a-zA-Z0-9.-]/g, '-')}`; const upload = await supabase.storage.from('posts').upload(path, image); if (upload.error) { setMessage('Não foi possível carregar a imagem.'); setSaving(false); return }; imageUrl = supabase.storage.from('posts').getPublicUrl(path).data.publicUrl }
    const { error } = await supabase.from('posts').insert({ title, slug, content, image_url: imageUrl, published: true }); if (error) setMessage('Crie a tabela posts no Supabase antes de publicar.'); else { setTitle(''); setContent(''); setImage(null); setShowForm(false); loadPosts() } setSaving(false)
  }
  async function togglePost(post: Post) { await supabase.from('posts').update({ published: !post.published, updated_at: new Date().toISOString() }).eq('id', post.id); loadPosts() }
  async function removePost(id: string) { if (!confirm('Eliminar este artigo?')) return; await supabase.from('posts').delete().eq('id', id); loadPosts() }
  return <main className="admin-editor-shell"><header className="admin-editor-header"><div><p className="admin-eyebrow">PAINEL DE CONTEÚDO</p><h1>Os seus artigos.</h1><p>Publique fotografias e histórias para o site público.</p></div><div className="admin-editor-actions"><span>{userEmail}</span><button className="admin-logout-button" onClick={logout}><LogOut aria-hidden="true" /> Sair</button></div></header><section className="admin-editor-toolbar"><div><strong>{posts.length}</strong><span>artigos publicados</span></div><button className="admin-primary-button" onClick={() => setShowForm(true)}><Plus aria-hidden="true" /> Novo artigo</button></section>{message && <p className="admin-form-message" role="alert">{message}</p>}{showForm && <form className="admin-post-form" onSubmit={createPost}><div className="admin-form-heading"><div><p className="admin-eyebrow">NOVO ARTIGO</p><h2>Publicar conteúdo</h2></div><button type="button" onClick={() => setShowForm(false)} aria-label="Fechar"><X /></button></div><label>Título<input required value={title} onChange={(e) => setTitle(e.target.value)} placeholder="Título do artigo" /></label><label>Texto<textarea required rows={7} value={content} onChange={(e) => setContent(e.target.value)} placeholder="Escreva o seu artigo..." /></label><label className="admin-upload-label"><span><ImagePlus aria-hidden="true" /> Fotografia de capa</span><input type="file" accept="image/*" onChange={(e) => setImage(e.target.files?.[0] ?? null)} />{image && <small>{image.name}</small>}</label><button disabled={saving} className="admin-primary-button" type="submit"><Upload aria-hidden="true" /> {saving ? 'A publicar...' : 'Publicar artigo'}</button></form>}<section className="admin-posts-list"><div className="admin-section-title"><div><p className="admin-eyebrow">BIBLIOTECA</p><h2>Artigos e fotografias</h2></div></div>{posts.length === 0 ? <div className="admin-empty"><FileText aria-hidden="true" /><strong>Ainda não existem artigos.</strong><span>Comece a publicar o primeiro conteúdo.</span></div> : posts.map((post) => <article className="admin-post-row" key={post.id}>{post.image_url ? <img src={post.image_url} alt="" /> : <div className="admin-post-placeholder"><FileText aria-hidden="true" /></div>}<div><strong>{post.title}</strong><span>{post.content.slice(0, 100)}</span></div><em className={post.published ? 'is-published' : ''}>{post.published ? 'Publicado' : 'Rascunho'}</em><button onClick={() => togglePost(post)}>{post.published ? 'Despublicar' : 'Publicar'}</button><button className="admin-delete-button" onClick={() => removePost(post.id)} aria-label={`Eliminar ${post.title}`}><Trash2 /></button></article>)}</section></main>
}
