import Link from 'next/link'
import { redirect } from 'next/navigation'
import { ImagePlus, FileText, LogOut, ExternalLink } from 'lucide-react'
import { createClient } from '@/lib/supabase/server'

export default async function AdminPanelPage() {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) redirect('/admin')
  const [{ data: photos }, { data: articles }, { data: contacts }] = await Promise.all([
    supabase.from('photos').select('id,title,detail').order('created_at', { ascending: false }),
    supabase.from('articles').select('id,title,category,published').order('created_at', { ascending: false }),
    supabase.from('contact_requests').select('id,name,subject,created_at').order('created_at', { ascending: false }).limit(10),
  ])
  return <main className="admin-panel-shell"><aside className="admin-sidebar"><Link href="/" className="admin-brand"><span>MV</span><b>ADVOGADO</b></Link><div className="admin-sidebar-label">GESTÃO DO SITE</div><nav className="admin-side-nav"><a className="is-active" href="#fotos">Fotos</a><a href="#artigos">Artigos</a><a href="#contactos">Pedidos</a><a href="/#contactos">Ver site público <ExternalLink /></a></nav><a className="admin-logout" href="/admin"><LogOut /> Sair</a></aside><section className="admin-content"><header className="admin-topbar"><div><p className="admin-kicker">MV-ADVOGADO</p><h1>PAINEL ADMINISTRATIVO</h1></div><div className="admin-avatar">{user.email?.charAt(0).toUpperCase()}</div></header><div className="admin-welcome"><p>Olá, {user.email}</p><span>Gerencie os conteúdos que aparecem no website institucional.</span></div><div className="admin-actions"><button type="button"><ImagePlus /> Adicionar Foto</button><button type="button"><FileText /> Criar Artigo</button></div><section id="fotos" className="admin-section"><div className="admin-section-heading"><div><p className="admin-kicker">BIBLIOTECA VISUAL</p><h2>Fotos</h2></div><span>{photos?.length ?? 0} itens</span></div><div className="admin-list">{photos?.map((photo) => <article className="admin-list-item" key={photo.id}><div className="admin-item-icon"><ImagePlus /></div><div className="admin-item-copy"><h3>{photo.title}</h3><p>{photo.detail}</p></div></article>)}</div></section><section id="artigos" className="admin-section"><div className="admin-section-heading"><div><p className="admin-kicker">PUBLICAÇÕES</p><h2>Artigos</h2></div><span>{articles?.length ?? 0} itens</span></div><div className="admin-list">{articles?.map((article) => <article className="admin-list-item" key={article.id}><div className="admin-item-icon"><FileText /></div><div className="admin-item-copy"><h3>{article.title}</h3><p>{article.category} · {article.published ? 'Publicado' : 'Rascunho'}</p></div></article>)}</div></section><section id="contactos" className="admin-section"><div className="admin-section-heading"><div><p className="admin-kicker">PEDIDOS RECEBIDOS</p><h2>Contactos</h2></div><span>{contacts?.length ?? 0} recentes</span></div><div className="admin-list">{contacts?.map((contact) => <article className="admin-list-item" key={contact.id}><div className="admin-item-copy"><h3>{contact.name}</h3><p>{contact.subject} · {new Date(contact.created_at).toLocaleDateString('pt-PT')}</p></div></article>)}</div></section></section></main>
}
